/**
 * Reference pages — shared shell guardrail
 *
 * Run: npm run test:reference-pages
 *
 * Three pages are GENERATED by cloning a live part page's shell: the Glossary,
 * The Framework in Pictures, and The Framework in Math. The clone keeps the
 * reference surface identical to the reading surface, which is the point — and
 * it also drags along the donor's place IN THE SERIES. Part 6 is the donor, so
 * every clone inherits a "← Part 5 · Series complete" dock and a "next up"
 * band, on pages that are not in the series at all.
 *
 * All three generators stripped the band from the start. Only the glossary
 * stripped the dock (2026-09-15), so Pictures and Math advertised a position in
 * the series for as long as they had existed, and nothing said so. The rule now
 * has one home (`scripts/site-b-shell.mjs`); these assertions pin the OUTPUT, so
 * a future generator that forgets to call it reddens here rather than shipping.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');

/** The generated reference pages, by the route a reader sees. */
const REFERENCE_PAGES = [
  { route: '/glossary', file: 'public/site-b/glossary.html', generator: 'scripts/build-glossary-page.mjs' },
  { route: '/framework-in-pictures', file: 'public/site-b/framework-in-pictures.html', generator: 'scripts/build-pictures-page.mjs' },
  { route: '/framework-in-math', file: 'public/site-b/framework-in-math.html', generator: 'scripts/build-math-page.mjs' },
];

/** The donor, which legitimately carries the chain and must keep it. */
const DONOR = 'public/site-b/part-6-convexity-scoring.html';

const dockOf = (html) => {
  const start = html.indexOf('<nav class="floatnav"');
  assert.notEqual(start, -1, 'the page carries a floating dock');
  const end = html.indexOf('</nav>', start);
  return html.slice(start, end);
};

test('reference pages: none advertises a place in the six-part series', () => {
  for (const page of REFERENCE_PAGES) {
    const html = read(page.file);
    assert.doesNotMatch(html, /floatnav-prev/, `${page.route} carries a prev link in the dock`);
    assert.doesNotMatch(html, /floatnav-next/, `${page.route} carries a next link in the dock`);
    assert.doesNotMatch(html, /class="next-up"/, `${page.route} carries a next-up band`);
    assert.doesNotMatch(html, /Series complete/, `${page.route} claims the series is complete`);
  }
});

test('reference pages: the dock keeps Back-to-top and the Framework home link', () => {
  // Stripping the chain must not strip the dock's own navigation with it.
  for (const page of REFERENCE_PAGES) {
    const dock = dockOf(read(page.file));
    assert.match(dock, /class="floatnav-top"/, `${page.route} lost Back-to-top`);
    assert.match(dock, /class="floatnav-home"/, `${page.route} lost the Framework home link`);
    assert.match(dock, /aria-label="Back to top"/, `${page.route} lost the Back-to-top label`);
  }
});

test('reference pages: the dock is marked chainless, so the phone keeps a destination', () => {
  // The site-wide mobile rule hides the Framework/home segment because "its room
  // goes to the Part links" — true on a part page, false here. Without the mark
  // a phone reader gets a lone Back-to-top button trailed by the divider that
  // used to precede the home link. Measured at 390 wide: dock 70px before the
  // exception, 232px with Back-to-top and Framework both rendered, after.
  for (const page of REFERENCE_PAGES) {
    assert.match(read(page.file), /<nav class="floatnav" data-no-series/, `${page.route} marks its dock chainless`);
  }
  const partPage = read(DONOR);
  assert.doesNotMatch(partPage, /data-no-series/, 'a page IN the series is never marked chainless');

  const css = read('public/site-b/reading-system.css');
  const mobile = css.slice(css.indexOf('@media (max-width: 600px)'));
  const block = mobile.slice(0, mobile.indexOf('\n}\n'));   // to the media block's own closing brace
  assert.match(block, /\.floatnav-home, \.floatnav-home \+ \.floatnav-div \{ display: none; \}/, 'the site-wide rule still stands');
  assert.match(block, /\.floatnav\[data-no-series\] \.floatnav-home \{ display: inline-flex; \}/, 'and its exception lives beside it');
  assert.ok(
    block.indexOf('data-no-series') > block.indexOf('.floatnav-home, .floatnav-home + .floatnav-div'),
    'the exception must come AFTER the rule it overrides — at equal specificity, source order decides'
  );
});

test('reference pages: every generator routes through the one shared rule', () => {
  // Three copies of a rule is how two of them drifted. If a generator stops
  // calling the shared helper, the output pins above are the net; this pin is
  // the earlier warning, naming the file that has to change.
  for (const page of REFERENCE_PAGES) {
    const src = read(page.generator);
    assert.match(src, /import \{ stripSeriesChain \} from '\.\/site-b-shell\.mjs'/, `${page.generator} imports the shared rule`);
    assert.match(src, /stripSeriesChain\(html, '[^']+'\)/, `${page.generator} calls it`);
    assert.doesNotMatch(src, /replace\([^)]*next-up/, `${page.generator} keeps no private copy of the rule`);
  }
});

test('shared rule: fails closed rather than silently shipping the chain', () => {
  const src = read('scripts/site-b-shell.mjs');
  assert.match(src, /floatnav-prev\|floatnav-next\|class="next-up"/, 'it re-checks its own work');
  assert.match(src, /process\.exit\(1\)/, 'and stops the build when the check fails');
  assert.match(src, /floatnav-top/, 'it also guards the dock keeping its own controls');
});

test('the donor keeps its chain — this is a reference-page rule, not a site-wide one', () => {
  // Part 6 IS in the series; a fix that reached the reading pages would be a
  // regression, not a broader success.
  const dock = dockOf(read(DONOR));
  assert.match(dock, /floatnav-prev/, 'Part 6 keeps its prev link');
  assert.match(dock, /floatnav-next/, 'Part 6 keeps its next slot');
});
